---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: secret-store
spec:
  provider:
    gcpsm:
      projectID: projets-pic-ts-sud-est-mtp
      auth:
        workloadIdentity:
          # name of the cluster region
          clusterLocation: europe-west1-d
          # name of the GKE cluster
          clusterName: pic
          # reference the sa from above
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets

...