# ---
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: argocd-client-external-secrets
#   namespace: argocd
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     kind: ClusterSecretStore
#     name: secret-store
#   target:
#     name: argocd-generic-oauth-secret
#     creationPolicy: Owner
#     template:
#       metadata:
#         labels:
#           app.kubernetes.io/component: server
#           app.kubernetes.io/instance: argo-cd
#           app.kubernetes.io/name: argocd-server
#           app.kubernetes.io/part-of: argocd
#       data:
#         clientID: "{{ .client_id }}"
#         clientSecret: "{{ .client_secret }}"
#   data:
#     - secretKey: client_secret  # key in the kubernetes secret
#       remoteRef:
#         key:  GOOGLE_CLIENT_SECRET_ARGO

#     - secretKey: client_id  # key in the kubernetes secret
#       remoteRef:
#         key:  GOOGLE_CLIENT_ID_ARGO
#   #      version: latest_enabled
# ...