project:

  # Name of the project: lowercase whithout spaces (kebab-case)
  name: ugap-ucloud
  description: "ugap-ucloud"

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - https://github.gsissc.myatos.net/FR-MTP-TSSUDEST/dx_ucloud_api.git
  - https://github.gsissc.myatos.net/FR-MTP-TSSUDEST/dx_ucloud_webapp.git

  # Only permit applications to deploy to specific namespace in the same cluster
  destinations:
  # - server: https://connectgateway.googleapis.com/v1beta1/projects/561688137130/locations/global/gkeMemberships/atos-dx-pf-logement-aca2-pf-logement-int
  - server: https://104.199.100.204
    namespace: '*'

# Project repositories
repositories:
- type: git
  url: https://github.gsissc.myatos.net/FR-MTP-TSSUDEST/dx_ucloud_api.git
  username: SV000236
  key: ARGO_GITHUB_TOKEN

- type: git
  url: https://github.gsissc.myatos.net/FR-MTP-TSSUDEST/dx_ucloud_webapp.git
  username: SV000236
  key: ARGO_GITHUB_TOKEN

# Project charts (can be 1 umbrella chart, or multiple charts)
applications:
  # deploy to integration 
  - name: ugap-ucloud-api-integration
    repoURL: https://github.gsissc.myatos.net/FR-MTP-TSSUDEST/dx_ucloud_api.git
    repoRevision: develop
    chart: .helm/api
    destination:
      #server: https://connectgateway.googleapis.com/v1beta1/projects/561688137130/locations/global/gkeMemberships/atos-dx-pf-logement-aca2-pf-logement-int
      server: https://104.199.100.204
      namespace: ucloud-api-integration
    helm:
      valueFiles:
        - values.integration.yaml
      parameters:
        - name: image.tag
          value: sha-${ARGOCD_APP_REVISION}        
  # deploy to integration 
  - name: ugap-ucloud-frontend-integration
    repoURL: https://github.gsissc.myatos.net/FR-MTP-TSSUDEST/dx_ucloud_webapp.git
    repoRevision: develop
    chart: .helm/frontend
    destination:
      #server: https://connectgateway.googleapis.com/v1beta1/projects/561688137130/locations/global/gkeMemberships/atos-dx-pf-logement-aca2-pf-logement-int
      server: https://104.199.100.204
      namespace: ucloud-frontend-integration
    helm:
      valueFiles:
        - values.integration.yaml
      parameters:
        - name: image.tag
          value: sha-${ARGOCD_APP_REVISION}

    # deploy to recette 
  - name: ugap-ucloud-frontend-recette
    repoURL: https://github.gsissc.myatos.net/FR-MTP-TSSUDEST/dx_ucloud_webapp.git
    repoRevision: main
    chart: .helm/frontend
    destination:
      server: https://104.199.100.204
      namespace: ucloud-frontend-recette
    helm:
      valueFiles:
        - values.recette.yaml
      parameters:
        - name: image.tag
          value: sha-${ARGOCD_APP_REVISION}

  - name: ugap-ucloud-api-recette
    repoURL: https://github.gsissc.myatos.net/FR-MTP-TSSUDEST/dx_ucloud_api.git
    repoRevision: main
    chart: .helm/api
    destination:
      server: https://104.199.100.204
      namespace: ucloud-api-recette
    helm:
      valueFiles:
        - values.recette.yaml
      parameters:
        - name: image.tag
          value: sha-${ARGOCD_APP_REVISION}
